Feature/wagtail cms
iotgdev/launch4d pull request #2
Opened 2020-10-05 10:40 UTC by VadymP-python

2020-10-08 11:01 UTC, iamwillburn commented
I tried to get this running, but hit quickly hit a wall where I can't get the docker image to build.

This is the command I ran, `docker build --tag lanch4d .`, and I got the error:
```
Collecting libsass==0.20.1
  Downloading libsass-0.20.1-cp36-abi3-manylinux1_x86_64.whl (9.4 MB)
Collecting openpyxl==3.0.5
  Downloading openpyxl-3.0.5-py2.py3-none-any.whl (242 kB)
Collecting Pillow==7.2.0
  Downloading Pillow-7.2.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r /requirements.txt (line 23)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r /requirements.txt (line 23))
WARNING: You are using pip version 20.0.2; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install -r /requirements.txt' returned a non-zero code: 1
```

I'm aware that I may be missing some steps to get this running locally but couldn't find anything in the codebase to help me, such as what is expected in terms of a database. Could you update the ReadMe file with step by step instructions?

2020-10-09 13:26 UTC, Nathan-Oliver requested changes
couldn't get this working:
- problem dependency versions in the requirements.txt file (pkg-resources==0.0.0)
- missing dependencies in pypi in the requirements.txt file (wagtail-svgmap==0.1.2)
- incorrect directory references in the dockerfile (can't copy launch4d_)
- incorrect file references in the dockerfile (can't run manage.py)

2020-10-13 17:15 UTC, Nathan-Oliver requested changes
This is really cool and i think the models you have designed will be perfect for the marketing team to manage the site. I have requested a few changes, and it would be excellent if we could remove the code that causes the yellow error screens to be shown in development. There is also an additional optional task to bring the form behaviour from it's lambda function back to this app. All in all though, excellent work

2020-10-13 17:15 UTC, Nathan-Oliver commented on home/models.py
> +            if isinstance(image, StructValue)
should this be `if isinstance(image.value, StructValue)` (just like the single image case?)

2020-10-13 17:15 UTC, Nathan-Oliver commented on home/models.py
> +                "url": image.value.file.url,
you could do something like `"url": image.value.file.url if image.value else ""` to prevent the yellow screens occurring when the images are not present on the sections

2020-10-18 17:49 UTC, VadymP-python commented on home/models.py
> +    favicons = StreamField(
if we move the favicon to the base page it would mean that the favicon should be populated for each new page

2020-10-18 17:55 UTC, VadymP-python commented on home/models.py
> +            if isinstance(image, StructValue)
I think no because we can both use SVG, and png, jpg and etc format of images, thus this check is required, or I misunderstood you?

2020-10-18 17:58 UTC, VadymP-python commented on home/templates/home/breadcumb/service_section.html
> +					<div class="careers__section">
What kind of customization should be implemented?

2020-10-21 13:44 UTC, Nathan-Oliver approved these changes
nice work vadym

2020-10-21 13:44 UTC, merged